##Applied Data Science

##Assignment - 1

##Name: Tatineni Jayanth

##Registration Number: 20BCB7048

##Q - 1

In [ ]:
Name = 'Jayanth Tatineni'
Age = 21

def my_func():
  print('My Name is:', Name)
  print('My Age is:', Age)

In [ ]:
my_func()

My Name is: Jayanth Tatineni
My Age is: 21


##Q - 2

In [ ]:
X="Datascience is used to extract meaningful insights."

print(X.split())

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


##Q - 3

In [ ]:
def multiplication(x,y):
  z = x*y
  print("Multiplication of {} and {} is: {}".format(x,y,z))

In [ ]:
x = int(input("Enter 1st Number: "))
y = int(input("Enter 2nd Number: "))

Enter 1st Number: 12
Enter 2nd Number: 10


In [ ]:
multiplication(x,y)

Multiplication of 12 and 10 is: 120


##Q - 4

In [ ]:
dict = {"Andhra Pradesh": "Amaravati",
        "Uttar Pradesh": "Lucknow",
        "Uttarakhand": "Dehradun",
        "Gujarat": "Gandhinagar",
        "Maharashtra": "Mumbai"}

In [ ]:
print(dict.keys())

dict_keys(['Andhra Pradesh', 'Uttar Pradesh', 'Uttarakhand', 'Gujarat', 'Maharashtra'])


In [ ]:
print(dict.values())

dict_values(['Amaravati', 'Lucknow', 'Dehradun', 'Gandhinagar', 'Mumbai'])


In [ ]:
print(dict)

{'Andhra Pradesh': 'Amaravati', 'Uttar Pradesh': 'Lucknow', 'Uttarakhand': 'Dehradun', 'Gujarat': 'Gandhinagar', 'Maharashtra': 'Mumbai'}


##Q - 5

In [ ]:
list = [*range(0,1000)]
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

##Q - 6

In [ ]:
import numpy as np

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##Q - 7

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Q - 8

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[4,5,9],[1,3,6],[2,8,7]])

res_arr = arr1 + arr2
print(res_arr)

[[ 5  7 12]
 [ 5  8 12]
 [ 9 16 16]]


##Q - 9

In [ ]:
import pandas as pd

dates = pd.date_range(start = '2023-02-01', end = '2023-03-01', freq='D')

s = pd.Series(dates)
print(s)

0    2023-02-01
1    2023-02-02
2    2023-02-03
3    2023-02-04
4    2023-02-05
5    2023-02-06
6    2023-02-07
7    2023-02-08
8    2023-02-09
9    2023-02-10
10   2023-02-11
11   2023-02-12
12   2023-02-13
13   2023-02-14
14   2023-02-15
15   2023-02-16
16   2023-02-17
17   2023-02-18
18   2023-02-19
19   2023-02-20
20   2023-02-21
21   2023-02-22
22   2023-02-23
23   2023-02-24
24   2023-02-25
25   2023-02-26
26   2023-02-27
27   2023-02-28
28   2023-03-01
dtype: datetime64[ns]


##Q - 10

In [ ]:
import pandas as pd

cars = {'Brand': ['Maruti', 'Renault', 'Hyndai'],
        'Sales': ['250', '200', '240']}
new = pd.DataFrame.from_dict(cars)

print(new)

     Brand Sales
0   Maruti   250
1  Renault   200
2   Hyndai   240
